// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BottomCopyright: typeof import('./src/components/footer/BottomCopyright.vue')['default']
    BottomFooter: typeof import('./src/components/footer/BottomFooter.vue')['default']
    BottomSocials: typeof import('./src/components/footer/BottomSocials.vue')['default']
    CompanyLogo: typeof import('./src/components/icons/CompanyLogo.vue')['default']
    ConnectionStatus: typeof import('./src/components/ConnectionStatus.vue')['default']
    FPSCounter: typeof import('./src/components/FPSCounter.vue')['default']
    SocialIcon: typeof import('./src/components/footer/SocialIcon.vue')['default']
  }
}

export { }
