// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AverageIcon: typeof import('./src/components/icons/AverageIcon.vue')['default']
    BottomCopyright: typeof import('./src/components/footer/BottomCopyright.vue')['default']
    BottomFooter: typeof import('./src/components/footer/BottomFooter.vue')['default']
    BottomSocials: typeof import('./src/components/footer/BottomSocials.vue')['default']
    CompanyLogo: typeof import('./src/components/icons/CompanyLogo.vue')['default']
    ConnectionStatus: typeof import('./src/components/state/ConnectionStatus.vue')['default']
    FPSCounter: typeof import('./src/components/state/FPSCounter.vue')['default']
    Header: typeof import('./src/components/header/Header.vue')['default']
    InfoBox: typeof import('./src/components/state/InfoBox.vue')['default']
    LaserBeamIcon: typeof import('./src/components/icons/LaserBeamIcon.vue')['default']
    MicrowaveIcon: typeof import('./src/components/icons/MicrowaveIcon.vue')['default']
    PacketIcon: typeof import('./src/components/icons/PacketIcon.vue')['default']
    QubeDisplay: typeof import('./src/components/qube/graph/QubeDisplay.vue')['default']
    QubeGraph: typeof import('./src/components/qube/graph/QubeGraph.vue')['default']
    QubeVideo: typeof import('./src/components/qube/QubeVideo.vue')['default']
    SocialIcon: typeof import('./src/components/footer/SocialIcon.vue')['default']
    SpeedIcon: typeof import('./src/components/icons/SpeedIcon.vue')['default']
    StatisticsCard: typeof import('./src/components/qube/graph/StatisticsCard.vue')['default']
    TemperatureIcon: typeof import('./src/components/icons/TemperatureIcon.vue')['default']
    UptimeIcon: typeof import('./src/components/icons/UptimeIcon.vue')['default']
  }
}

export { }
